config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  get "posts/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # Defines the root path route ("/")
  root "static_pages#top"

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :users, only: %i[new create]
  resources :posts, only: %i[index new create show edit update destroy] do
    resources :comments, only: %i[create edit update destroy show], shallow: true
    collection do
      get :bookmarks
    end
    member do
      patch :emo_reactions
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 65_535 }

  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [ :edit, :update, :destroy, :show ]

  def create
    @comment = current_user.comments.build(comment_create_params)
    @comment.save
  end

  def edit; end

  def show; end

  def update
    @comment.update(comment_update_params)
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def set_comment
    @comment = current_user.comments.find(params[:id])
  end

  def comment_create_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end

  def comment_update_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>" class="border border-gray-300 bg-gray-50 rounded-md p-3 mb-3">
  <h3 class="text-sm font-semibold text-gray-800"><%= comment.user.name %></h3>
  <p class="text-gray-700 whitespace-pre-line"><%= simple_format(comment.body) %></p>

  <!-- ログインユーザーかつ自分の投稿であれば表示 -->
  <% if current_user && current_user.own?(comment) %>
    <div class="flex justify-end space-x-4 mt-2">
      <%= link_to edit_comment_path(comment), data: { turbo_stream: true }, class: "text-blue-600 hover:underline" do %>
        <%= image_tag "icon_pen.svg", alt: "delete", class: "w-4 h-4 mr-1" %>
      <% end %>
      <%= link_to comment_path(comment),  data: { turbo_method: :delete, turbo_confirm: t('defaults.delete_confirm') }, class: "text-red-600 hover:underline" do %>
        <%= image_tag "icon_trash.svg", alt: "delete", class: "w-4 h-4 mr-1" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/comments/_edit_form.html.erb
<div class="border border-gray-300 rounded-md p-3 mb-3" id="comment-edit-<%= comment.id %>">
  <%= form_with model: comment, url: comment_path(comment) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :body, class: "block text-sm font-medium text-gray-700 mb-1" %>
    <%= f.text_area :body, class: "w-full border rounded p-2 mb-3 focus:outline-none focus:ring focus:ring-blue-300", rows: "4" %>
    <div class="flex justify-end space-x-2">
      <%= f.submit "更新", class: "bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700" %>
      <%= link_to "キャンセル", comment_path(comment), class: "bg-gray-500 text-white px-4 py-2 rounded hover:bg-gray-600", data: { turbo_stream: true } %>
    </div>
  <% end %>
</div>

app/views/comments/_form.html.erb
<div class="mb-4" id="comment-form">
  <div class="">
    <%= form_with model: comment, url: post_comments_path(post) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :body %>
      <%= f.text_area :body, class: "w-full border rounded p-2 mb-3 focus:outline-none focus:ring focus:ring-blue-300", row: "4", placeholder: Comment.human_attribute_name(:body) %>
      <%= f.submit t('defaults.post'), class: "bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700" %>
    <% end %>
  </div>
</div>

app/views/comments/create.turbo_stream.erb
<% if @comment.errors.present? %>
  <!-- エラー時にはフォームがそのまま表示 -->
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: @comment, post: @comment.post %>
  <% end %>
<% else %>
  <!-- 新しいコメントを追加 -->
  <%= turbo_stream.prepend "table-comment" do %>
    <%= render 'comments/comment', comment: @comment %>
  <% end %>
  <!-- 空のフォーム -->
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: Comment.new, post: @comment.post %>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment-#{@comment.id}" %>

app/views/comments/edit.turbo_stream.erb
<%= turbo_stream.replace "comment-#{@comment.id}" do %>
  <%= render 'comments/edit_form', comment: @comment %>
<% end %>

app/views/comments/show.turbo_stream.erb
<%= turbo_stream.replace "comment-edit-#{@comment.id}" do %>
  <%= render 'comments/comment', comment: @comment %>
<% end %>

app/views/comments/update.turbo_stream.erb
<% if @comment.errors.present? %>
  <!-- エラー内容や入力値を保持したままフォームを再表示 -->
  <%= turbo_stream.replace "comment-edit-#{@comment.id}" do %>
    <%= render 'comments/edit_form', comment: @comment %>
  <% end %>
<% else %>
  <%= turbo_stream.replace "comment-edit-#{@comment.id}" do %>
    <%= render 'comments/comment', comment: @comment %>
  <% end %>
<% end %>