config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  get "posts/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # Defines the root path route ("/")
  root "static_pages#top"

  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"

  resources :users, only: %i[new create]
  resources :posts, only: %i[index new create show edit update destroy] do
    resources :comments, only: %i[create edit update destroy show], shallow: true
    collection do
      get :bookmarks
    end
    member do
      patch :emo_reactions
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_path, success: t("user_sessions.create.success")
    else
      flash.now[:danger] = t("user_sessions.create.failure")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, success: t("user_sessions.destroy.success")
  end
end

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="flex items-center justify-center min-h-screen bg-gray-300">
  <div class="w-full max-w-sm bg-white rounded-2xl shadow-lg p-8">
    <h1 class="text-xl font-semibold mb-4 text-center"><%= t('.title') %></h1>
    <%= form_with url: login_path, local: true do |f| %>
      <div class="mb-4">
        <%= f.label :email, class: "block text-sm font-medium text-gray-700 mb-1" %>
        <%= f.email_field :email, class: "w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none" %>
      </div>
      <div class="mb-6">
        <%= f.label :password, class: "block text-sm font-medium text-gray-700 mb-1" %>
        <%= f.password_field :password, class: "w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none" %>
      </div>
      <%= f.submit t('.login'), class: "w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition duration-200 font-semibold" %>
    <% end %>
    <div class='mt-1 text-center text-sm text-blue-600 font-medium space-y-1'>
      <%= link_to t('.password_forget'), new_password_reset_path %>
    </div>
    <div class="my-6 flex items-center">
      <div class="flex-grow border-t border-gray-300"></div>
      <span class="mx-3 text-xs text-gray-500">または</span>
      <div class="flex-grow border-t border-gray-300"></div>
    </div>
    <div class="flex items-center justify-center">
      <%= link_to auth_at_provider_path(provider: :google) do %>
        <%= image_tag "web_light_rd_SI.svg", alt: "Google" %>
      <% end %>
    </div>
  </div>
</div>